---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: almalinux-8
    box: almalinux/8
    memory: 2048
    cpus: 2
  - name: almalinux-9
    box: almalinux/9
    memory: 2048
    cpus: 2
provisioner:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint --exclude molecule

verifier:
  name: testinfra
  options:
    v: true

scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
