---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: almalinux-8
    box: almalinux/8
    memory: 1024
    cpus: 1
provisioner:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint

verifier:
  name: testinfra
  options:
    v: true

scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
