---
mlnx_ofed_url: 'https://content.mellanox.com/ofed/MLNX_OFED-5.4-3.0.3.0/MLNX_OFED_LINUX-5.4-3.0.3.0-rhel8.4-x86_64.tgz'
mlnx_ofed_checksum: 'sha256:6a5c6eb2abcbf61528cef081b4ce35baa825b1da39a70705eef660de8fefe1d2'
