---
- name: Detect kernel version
  command: uname -r
  register: mlnx_ofed_uname_rslt

- name: Install common dependencies
  dnf:
    name:
      - gcc
      - gcc-gfortran
      - "kernel-devel-{{ mlnx_ofed_uname_rslt.stdout }}"
      - kernel-rpm-macros
      - libtool
      - lsof
      - make
      - patch
      - python3-dnf-plugin-versionlock
      - rpm-build
      - tk
      - tcsh

- name: Install EL8 build dependencies
  dnf:
    name:
      - '@perl/minimal'
      - '@python36/build'
      - "kernel-modules-extra-{{ mlnx_ofed_uname_rslt.stdout }}"
      - elfutils-libelf-devel
    state: present
  when: ansible_facts['distribution_major_version'] == '8'

- name: Install EL9 build dependencies
  dnf:
    name:
      - perl
      - python3-devel
      - libusbx
      - tcl
    state: present
  when: ansible_facts['distribution_major_version'] == '9'

- name: Create Mellanox OFED temporary directory
  tempfile:
    path: /root
    state: directory
    prefix: mlnx_ofed_
  register: mlnx_ofed_tmp

- name: Download drivers tarball
  get_url:
    url: "{{ mlnx_ofed_url if ansible_facts['distribution_major_version'] == '8' else mlnx_ofed_9_url }}"
    checksum: "{{ mlnx_ofed_checksum if ansible_facts['distribution_major_version'] == '8' else mlnx_ofed_9_checksum }}"
    dest: "{{ mlnx_ofed_tmp.path }}/MLNX_OFED.tgz"

- name: Unpack drivers tarball
  unarchive:
    src: "{{ mlnx_ofed_tmp.path }}/MLNX_OFED.tgz"
    dest: "{{ mlnx_ofed_tmp.path }}/"
    remote_src: true

- name: Find unpacked directory
  find:
    paths: "{{ mlnx_ofed_tmp.path }}/"
    file_type: directory
  register: mlnx_ofed_found_dirs

- name: Patch Mellanox OFED installer for AlmaLinux support
  replace:
    path: "{{ mlnx_ofed_found_dirs.files[0].path }}/common.pl"
    regexp: '(.*?)\(\$dist_rpm =~ /redhat-release-9\.0-/\)(.*?)$'
    replace: '\1($dist_rpm =~ /(redhat|almalinux)-release-9.0-/)\2'
  when: ansible_facts['distribution_major_version'] == '9'

- name: Run Mellanox OFED installer
  command: "{{ mlnx_ofed_found_dirs.files[0].path }}/mlnxofedinstall --kernel {{ mlnx_ofed_uname_rslt.stdout }} --kernel-sources /usr/src/kernels/{{ mlnx_ofed_uname_rslt.stdout }} --add-kernel-support --skip-repo"

- name: Update initramfs
  command: dracut -f

- name: Delete Mellanox OFED temporary directory
  file:
    path: "{{ mlnx_ofed_tmp.path }}"
    state: absent
  when: mlnx_ofed_tmp.path is defined

- name: Lock perftest package version
  command: dnf versionlock add perftest
  register: perftest_lock
  changed_when: "'Adding versionlock on: perftest' in perftest_lock.stdout"

- name: Lock openmpi package version
  command: dnf versionlock add openmpi
  register: openmpi_lock
  changed_when: "'Adding versionlock on: openmpi' in openmpi_lock.stdout"
